### ISSUE TITLE
Items won't spaw

### ISSUE THREAD

**Issue by Akkorcseszdmeg** [Krypton91/KR_KingOfTheHill#14]
We set the mod on our server but nothing spawns after someone capture the flag.

**Comment by Rocool21** [comment]
same happen to my server but in my case sometimes there's a loot sometimes non, minimum loot is 6 and max is 9

**Comment by MarkAC007** [comment]
Yup,  same here.  Seems a bit hit an miss.

**Comment by Rocool21** [comment]
[server-config.json.txt](https://github.com/Krypton91/KR_KingOfTheHill/files/9786362/server-config.json.txt)

**Comment by Krypton91** [comment]
and also the server scriptlog please.

**Comment by Rocool21** [comment]
[script_2022-10-14_20-00-23.log](https://github.com/Krypton91/KR_KingOfTheHill/files/9787145/script_2022-10-14_20-00-23.log)

**Comment by Krypton91** [comment]
Your Items are not spawing because you have typos in a classname. Be sure its correct and please read your server logs!

[KOTH] -> Cant create item in Container: SNAFUAX50_GUN maybe wrong classname of item in json!
Class:      'KR_KingOfTheHillZone'
Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:92
KR_KingOfTheHill/scripts/4_World/kingofthehillzone.c:255
KR_KingOfTheHill/scripts/4_World/kingofthehillzone.c:391
KR_KingOfTheHill/scripts/4_World/kingofthehillzone.c:354
KR_KingOfTheHill/scripts/4_World/kingofthehilleventmanager.c:131
KR_KingOfTheHill/scripts/5_Mission/missionserver.c:18
scripts/3_Game/dayzgame.c:2478
